name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.16.x, 1.15.x, 1.14.x, 1.13.x, 1.12.x, 1.11.x, 1.10.x, 1.9.x ]
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: auto
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/cweill/gotests
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/cweill/gotests

    - name: Get Dependencies (github.com/golang.org/x/tools/imports)
      run: go get -v ./...

    - name: Test
      run: |
        go test -v ./...

    - name: Coverage - Geting Report
      if: matrix.go == '1.16.x'
      run: |
        PKGS=$(go list ./... | grep -vE "(gotests/gotests|.*data|templates)" | tr -s '\n' ',' | sed 's/.\{1\}$//')
        echo "Generate covering for ${PKGS}"
        go test -v -covermode=count -coverpkg=$PKGS -coverprofile=coverage.out
        ls -la

    - name: Coverage - Converting coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.5
      if: matrix.go == '1.16.x'
      with:
          working-directory:  ${{ env.GOPATH }}/src/github.com/cweill/gotests/
          infile: ${{ env.GOPATH }}/src/github.com/cweill/gotests/coverage.out
          outfile: ${{ env.GOPATH }}/src/github.com/cweill/gotests/coverage.lcov

    - name: Coverage - reporting to Coveralls
      uses: coverallsapp/github-action@master
      if: matrix.go == '1.16.x'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ env.GOPATH }}/src/github.com/cweill/gotests/coverage.lcov
